apps:
- id: ingresscontroller
  name: Ingress Controller
- id: kubernetesdashboard
  name: Kubernetes Dashboard
- id: prometheus-grafana
  name: 'Monitoring: Prometheus & Grafana'
- id: argocs
  name: ArgoCD
- id: letsencrypt
  name: Cert-Manager LetsEncrypt
cluster:
  cloud:
    domain: shalb.net
    provider: digitalocean
    region: do-2
    vpc: myId
  installed: true
  name: minikube-aws
  provisioner:
    instanceType: n10-large
    type: clusterapi
