apps:
- default: true
  id: ingresscontroller
  name: Ingress Controller
  selected: true
- default: true
  id: loggingwithelk
  name: Logging with ELK
  selected: true
cluster:
  cloud:
    domain: shalb.net
    provider: aws
    region: eu-central-2
    vpc: myId
  installed: true
  name: minikube-aws
  provisioner:
    instanceType: n10-large
    type: clusterapi
